### ISSUE TITLE
Published iPython notebooks do not display properly if already logged in

### ISSUE THREAD

**Issue by maxlieblich** [sagemathinc/smc-public#1]
I created an iPython notebook and published it (in Safari), and followed the generated link (in Chrome) while logged in. SMC presented me with the html editor instead of displaying the page.

**Comment by williamstein** [comment]
This is intentional since SMC has an html editor.  To view what the published version looks like to others, open the link in a browser that isn't logged into SMC (or logged into an account that doesn't have access to that project). 

I might add to the html editor a link to the rendered html if there is a corresponding .ipynb file...

**Comment by maxlieblich** [comment]
Got it. It seems like a good idea to have some kind of default that will display the notebooks. This would give SMC a leg up over nbviewer, since one can then directly clone the notebook without having to have a local installation of the tools. Having different behavior for logged in/out users is confusing.

For example, I might want to make a final report for a class on their grades/performance/whatever, but I might want to add some kind of limited dynamic functionality. (E.g., a student might want to obsesses about what would have happened if he got two more points on the second midterm.) It would be natural to publish an iPython (or Jupyter) notebook. (This might also require transporting some data files along with it. OT: does importing a published ipynb also import the files that are loaded by cells? Presumably not, in which case what I'm suggesting might not work anyway.) If the student was already using SMC, then following a link could cause confusion. (Maybe the answer is to give it as an "assignment" via the course management functionality.)

I'm currently using knitr to produce reports. That locks me into R pretty hard.

**Comment by williamstein** [comment]
On Mon, Mar 23, 2015 at 2:30 PM, Max Lieblich notifications@github.com
wrote:

> Got it. It seems like a good idea to have some kind of default that will
> display the notebooks. This would give SMC a leg up over nbviewer, since
> one can then directly clone the notebook without having to have a local
> installation of the tools. Having different behavior for logged in/out
> users is confusing.
> 
> For example, I might want to make a final report for a class on their
> grades/performance/whatever, but I might want to add some kind of limited
> dynamic functionality. (E.g., a student might want to obsesses about what
> would have happened if he got two more points on the second midterm.) It
> would be natural to publish an iPython (or Jupyter) notebook. (This might
> also require transporting some data files along with it. OT: does importing
> a published ipynb also import the files that are loaded by cells?
> 
> You'll want to instead publish a directory, which can contain anything you
> want.  You can publish directories by clicking the "i" info icon and click
> "Make Public", then just share the link to the folder.  Other people who
> visit the folder can click "i" and "Copy to my project" to copy the
> contents of the folder to their own project.    There is no size limit on
> the folder.
> 
> Presumably not, in which case what I'm suggesting might not work anyway.)
> If the student was already using SMC, then following a link could cause
> confusion. (Maybe the answer is to give it as an "assignment" via the
> course management functionality.)

The issue isn't at all whether the student is logged in or not.  It's
whether they have write access to the project that is publishing the
notebook.    If the student view the public .html file for a notebook, but
isn't logged in as you (!), or isn't a collaborator on the project, they
see it properly rendered.

> I'm currently using knitr to produce reports. That locks me into R pretty
> hard.
> 
> ## 
> 
> Reply to this email directly or view it on GitHub
> https://github.com/sagemathinc/smc-public/issues/1#issuecomment-85205941
> .

## 

William (http://wstein.org)

**Comment by haraldschilly** [comment]
@maxlieblich another limit is, that published notebooks do not have any dynamic capabilities. so, I think this is yet another reason why this doesn't work. I wouldn't change the behaviour, since it actually has different purposes. Maybe, the "published" view needs to have a redesign at some point, to make it clear that this is only a static view.

regarding knitr: we "sagemath" people use http://www.sagemath.org/doc/tutorial/sagetex.html ... which is a bit more advanced than knitr but gives you the same. You can also run arbitrary python via sagetex, obviously. for generating plain HTML pages, standard tools like jinja2 are very helpful to spit out a lot of pages from a single template (and to mix everything up I just said, it's possible to generate latex files via jinja2 templates)

**Comment by maxlieblich** [comment]
Aha! Thx.

**Comment by haraldschilly** [comment]
btw: sagetex is supported out of the box in SMC's latex editor. copy/paste of the documentation "should just work"^:tm:

**Comment by williamstein** [comment]
And in case it isn't clear, you can also host arbitrary html-based web
pages on SageMathCloud.   For example, this page is hosted directly from a
project with data that gets updated regularly:

https://cloud.sagemath.com/7561f68d-3d97-4530-b97e-68af2fb4ed13/raw/stats.html

William

## 

William (http://wstein.org)

**Comment by maxlieblich** [comment]
This is all great. My only criticism is that it would be wonderful to make it drop-dead easy to do certain things. Want to generate an ipynb that requires some backend files/libs to also be present, etc. (hence publishing directory, etc.)? There should be one button for that. Want to write a Shiny app? One button!

I recognize that I'm making a bunch of demands and possibly suggesting terrible feature creep. Otoh, if I think of non-pure math audiences -- "teachers and students" or "data scientists" -- for whom a system like this is incredibly useful, even if they don't know the ins and outs of the terminal, I think they need serious handholding. I might be such a person myself!

**Comment by williamstein** [comment]
On Mon, Mar 23, 2015 at 2:51 PM, Max Lieblich notifications@github.com
wrote:

> This is all great. My only criticism is that it would be wonderful to make
> it drop-dead easy to do certain things. Want to generate an ipynb that
> requires some backend files/libs to also be present, etc. (hence publishing
> directory, etc.)? There should be one button for that. Want to write a
> Shiny app? One button!

Of course.  But to do that, one has to build the backend infrastructure
first, then make it available at all, then make it work 100%.  Making
documents public at all (and ipython notebooks) is itself _very_ new.  Even
copying documents between files only recently became much more robust.

I want everything you're saying, and plan to implement it.  However, it's a
careful strategic process, in which foundations must be properly built. My
responses above are mainly just letting you know how you can solve your
problems right now, while you wait for our army of programmers (=me) to
implement everything.

> I recognize that I'm making a bunch of demands and possibly suggesting
> terrible feature creep. Otoh, if I think of non-pure math audiences --
> "teachers and students" or "data scientists" -- for whom a system like this
> is incredibly useful, even if they don't know the ins and outs of the
> terminal, I think they need serious handholding. I might be such a person
> myself!
> 
> You might also notice that there is almost not documentation yet...  Maybe
> you can write something :-)
> 
> ## 
> 
> Reply to this email directly or view it on GitHub
> https://github.com/sagemathinc/smc-public/issues/1#issuecomment-85215986
> .

## 

William (http://wstein.org)

**Comment by maxlieblich** [comment]
Got it. Roadmap approved! ;)

**Comment by haraldschilly** [comment]
one-button solutions for "mashup"-style applications, i.e. where some elements are mixed together, usually never do what one really wants. but maybe there are some essential elements that can be simplified, it is very likely that something can be done. 

in case of ipython nb: what you actually ask for is a way to embed files inside a notebook. I'm mentioning this, because the development model (as far as I understand it) favours this approach. Currently, all plots are already embedded, so why not extend this to other files...

shiny is not supported btw. or to say it differently: I've tried but failed to run it properly.

**Comment by williamstein** [comment]
On Mon, Mar 23, 2015 at 2:59 PM, Harald Schilly notifications@github.com
wrote:

> one-button solutions for "mashup"-style applications, i.e. where some
> elements are mixed together, usually never do what one really wants. but
> maybe there are some essential elements that can be simplified, it is very
> likely that something can be done.
> 
> in case of ipython nb: what you actually ask for is a way to embed files
> inside a notebook. I'm mentioning this, because the development model (as
> far as I understand it) favours this approach. Currently, all plots are
> already embedded, so why not extend this to other files...
> 
> My reason: IPython notebook embeds files in their single text JSON format,
> via textual encodings of images (say), is kind of bad.  I don't really want
> to encourage it.     It makes synchronization across clients very
> inefficient and makes parallel loading of resource impossible. It seems
> hackish given that things like zip and tar exist.
> 
> shiny is not supported btw. or to say it differently: I've tried but
> failed to run it properly.
> 
> ## 
> 
> Reply to this email directly or view it on GitHub
> https://github.com/sagemathinc/smc-public/issues/1#issuecomment-85221448
> .

## 

William (http://wstein.org)

**Comment by williamstein** [comment]
New plan: when opening a static html file, if it was generated by nbconvert, just render it.  Simple as that.

**Comment by williamstein** [comment]
Moved to https://github.com/sagemathinc/smc/issues/5
