### ISSUE TITLE
Show keybindings for search functions

### ISSUE THREAD

**Issue by rbeezer** [sagemathinc/smc-public#10]
Easy and clear how to initiate a search.  But I frequently want to find the next occurence(s).  This [CodeMirror demo](https://codemirror.net/demo/search.html) gave me the clue I needed.

It would be great if some of these were include in the list of keybindings in the user settings page.  I could not find this in help or other place.  Sorry for the noise if I missed them.

Maybe this would be a good project for somebody who wants to get started contributing.

**Comment by williamstein** [comment]
The react-based version of account settings that I'm going to push out soon will include this setting.

**Comment by rbeezer** [comment]
Included in settings-page rewrite using React.  Thanks.
