### ISSUE TITLE
Add "most common used" to LaTeX editor

### ISSUE THREAD

**Issue by kcrisman** [sagemathinc/smc-public#12]
There are the little shortcuts in the sagews view, but one thing I like about things like TeXShop (and presumably are also in Overleaf and WriteLaTeX) is having most-commonly-used things in shortcuts or icons or something.  Currently I'm having trouble remembering matrix syntax for non-standard matrices so I have to look it up outside SMC :smiley: Perhaps you can also provide the "symbol table" from Grätzer like TeXShop does.

**Comment by williamstein** [comment]
Moved to https://github.com/sagemathinc/smc/issues/1
