### ISSUE TITLE
Ampersands in TeX filenames break preview

### ISSUE THREAD

**Issue by rbeezer** [sagemathinc/smc-public#2]
In `texput.log` you will see only as much of the filename as occurs prior to the & character.

**Comment by AndreWin** [comment]
Hi! Where can I see `texput.log`?

**Comment by williamstein** [comment]
I can't replicate this.  I think maybe this used to a bug, but I'm not seeing it right now... Hmm. 
![screen shot 2015-04-09 at 6 47 50 am](https://cloud.githubusercontent.com/assets/1276278/7068018/632657ee-de84-11e4-9961-ff4053b74eab.png)
![screen shot 2015-04-09 at 6 48 02 am](https://cloud.githubusercontent.com/assets/1276278/7068017/63249b16-de84-11e4-8bb6-d26ad4ec3ba9.png)

**Comment by rbeezer** [comment]
@williamstein - can you try a filename _with_ an ampersand and _without_ any spaces?  I definitely still see this (refreshes/restarts after major upgrade) and your example (with spaces) does preview properly (just checked that).  I'm going to guess the spaces induce some sort of protection (quoting) in some command-line somewhere, but otherwise an ampersand slips through un-protected (resulting in half a filename).

@AndreWin - right next to the original file.  But maybe you need a compile attempt with an error?  Try a tex file with a name like `a&b.tex`

**Comment by haraldschilly** [comment]
@rbeezer it might also depend on the character right after the ampersand. can you give us an exact filename where this happens for you?

**Comment by rbeezer** [comment]
Thanks, Harald.  I have been testing with `amper&sand.tex`.  Original report was `D&E-1.tex`, iirc.

**Comment by williamstein** [comment]
OK, replicated without space.  I'll find whatever code puts quotes in when
there is a space... and have it always put quotes in.

William

On Thu, Apr 9, 2015 at 7:49 AM, Rob Beezer notifications@github.com wrote:

> Thanks, Harald. I have been testing with amper&sand.tex. Original report
> was D&E-1.tex, iirc.
> 
> ## 
> 
> Reply to this email directly or view it on GitHub
> https://github.com/sagemathinc/smc-public/issues/2#issuecomment-91252953
> .

## 

William (http://wstein.org)

**Comment by rbeezer** [comment]
Thanks, glad it is genuine.  My linear algebra students, currently crafting proofs of facts from Chapters D _AND_ E, thank you as well.  ;-)
