### ISSUE TITLE
Move issues from previous

### ISSUE THREAD

**Issue by kcrisman** [sagemathinc/smc-public#4]
Move the issues from https://github.com/sagemath/cloud/issues to here.  There are lots there.

By the way, I don't quite get why sagemathinc should have this; the dependency graph will be a little complicated if the 'personal edition' makes it back into Sage...

**Comment by williamstein** [comment]
Any moved issues should get moved to https://github.com/sagemathinc/smc/issues

**Comment by kcrisman** [comment]
Okay, but did you open a new issue there for this?

Also, can you explain (perhaps on sage-devel) the _exact_ relationship between the sagemath/cloud, sagemathinc/smc, and sagemathinc/smc-public repos?  It looks really confusing to me, and probably to anyone.

**Comment by williamstein** [comment]
On Sat, Jun 6, 2015 at 6:30 PM, kcrisman notifications@github.com wrote:

> Okay, but did you open a new issue there for this?

No, I didn't.

> Also, can you explain (perhaps on sage-devel) the _exact_ relationship
> between the sagemath/cloud, sagemathinc/smc, and sagemathinc/smc-public
> repos? It looks really confusing to me, and probably to anyone.

sagemathinc/smc-public and sagemath/cloud are deprecated.

> —
> Reply to this email directly or view it on GitHub
> https://github.com/sagemathinc/smc-public/issues/4#issuecomment-109668863
> .

## 

William (http://wstein.org)
