### ISSUE TITLE
Explination of current smc

### ISSUE THREAD

**Issue by ZucchiniZe** [sagemathinc/smc-public#9]
Are there any resources explaining how sagemath cloud currently works?

**Comment by williamstein** [comment]
I wrote this

   https://github.com/sagemathinc/smc-public/blob/master/doc/dev/dev.md

however things have changed a lot and will change...

**Comment by ZucchiniZe** [comment]
Is there going to be a gitter room where we can talk quicker?

**Comment by williamstein** [comment]
We've had this for a while: https://gitter.im/sagemath/cloud

On Mon, Jun 1, 2015 at 7:18 PM, Alex B notifications@github.com wrote:

> Is there going to be a gitter room where we can talk quicker?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/sagemathinc/smc-public/issues/9#issuecomment-107774089
> .

## 

William (http://wstein.org)
